spring:
  application:
    name: bareum-server
  mail:
    properties:
      "[mail.smtp.connectiontimeout]": ${SMTP_CONNECTION_TIMEOUT_MS:5000}
      "[mail.smtp.timeout]": ${SMTP_READ_TIMEOUT_MS:5000}
      "[mail.smtp.writetimeout]": ${SMTP_WRITE_TIMEOUT_MS:5000}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: false
    out-of-order: false
    clean-disabled: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: org.hibernate.type.format.jackson.Jackson3JsonFormatMapper

springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false
  remove-broken-reference-definitions: false

scalar:
  enabled: true
  url: /v3/api-docs
  path: /scalar
  page-title: Bareum API
  theme: default
  layout: classic

auth:
  email-verification:
    hash-secret: ${EMAIL_VERIFICATION_HASH_SECRET}
    mail-from: ${EMAIL_VERIFICATION_MAIL_FROM:}
