spring:
  application:
    name: bareum-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: org.hibernate.type.format.jackson.Jackson3JsonFormatMapper

springdoc:
  api-docs:
    enabled: true
  override-with-generic-response: false
  remove-broken-reference-definitions: false

scalar:
  enabled: true
  url: /v3/api-docs
  path: /scalar
  page-title: Bareum API
  theme: default
  layout: classic
