CREATE TABLE email_verification_send_log (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             email VARCHAR(255) NOT NULL,
                                             purpose VARCHAR(30) NOT NULL,
                                             sent_at TIMESTAMPTZ NOT NULL,
                                             created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                             updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
