CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    signup_method VARCHAR(30) NOT NULL,
    withdrawn_at TIMESTAMPTZ,
    withdrawn_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE member_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES member(id),
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    linked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    unlinked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_user_id)
);

CREATE TABLE term (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    version VARCHAR(30) NOT NULL,
    is_required BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (code, version)
);

CREATE TABLE member_term (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES member(id),
    term_id BIGINT NOT NULL REFERENCES term(id),
    agreed_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    is_agreed BOOLEAN NOT NULL,
    responded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE email_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_sent_at TIMESTAMPTZ,
    verified_at TIMESTAMPTZ,
    verification_token_hash VARCHAR(255),
    verification_expires_at TIMESTAMPTZ,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL UNIQUE REFERENCES member(id),
    jti UUID NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES member(id),
    report_type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    file_format VARCHAR(30),
    input_method VARCHAR(30) NOT NULL,
    source_object_key TEXT,
    original_filename VARCHAR(255),
    file_size_bytes BIGINT,
    source_expires_at TIMESTAMPTZ,
    source_deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE report_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES report(id),
    content JSONB NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    is_current BOOLEAN NOT NULL DEFAULT false,
    revision BIGINT NOT NULL DEFAULT 1,
    base_content_id BIGINT REFERENCES report_content(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE report_parse_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES report(id),
    produced_content_id BIGINT UNIQUE REFERENCES report_content(id),
    process_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    extraction_quality VARCHAR(30),
    extraction_warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
    error_code VARCHAR(30),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE report_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES report_content(id),
    request_key UUID NOT NULL UNIQUE,
    total_score NUMERIC(5, 2),
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    failure_code VARCHAR(30),
    failure_reason TEXT,
    ruleset_version VARCHAR(255) NOT NULL,
    prompt_version VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE report_analysis_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_analysis_id BIGINT NOT NULL REFERENCES report_analysis(id),
    step_code VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    failure_code VARCHAR(30),
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (report_analysis_id, step_code)
);

CREATE TABLE report_analysis_area_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_analysis_id BIGINT NOT NULL REFERENCES report_analysis(id),
    deduction_score NUMERIC(5, 2),
    area_code VARCHAR(30) NOT NULL,
    result_detail JSONB,
    UNIQUE (report_analysis_id, area_code)
);

CREATE TABLE issue_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_analysis_id BIGINT NOT NULL REFERENCES report_analysis(id),
    target_id VARCHAR(255),
    scope VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_area_result_id BIGINT NOT NULL REFERENCES report_analysis_area_result(id),
    issue_group_id BIGINT NOT NULL REFERENCES issue_group(id),
    severity VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'UNPROCESSED',
    title VARCHAR(255) NOT NULL,
    reason TEXT NOT NULL,
    review_guidance TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE issue_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES issue(id),
    evidence_type VARCHAR(30) NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    source_locator VARCHAR(255),
    quoted_text TEXT NOT NULL,
    source_url TEXT,
    source_version VARCHAR(255),
    source_effective_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE issue_suggestion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES issue(id),
    changes JSONB NOT NULL,
    generation_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE report_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_analysis_id BIGINT NOT NULL REFERENCES report_analysis(id),
    content_id BIGINT NOT NULL REFERENCES report_content(id),
    final_score NUMERIC(5, 2),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    failure_code VARCHAR(30),
    completed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_report_content_current
    ON report_content (report_id) WHERE is_current = true;

CREATE UNIQUE INDEX uk_report_analysis_success
    ON report_analysis (content_id) WHERE status = 'SUCCEEDED';
